#!/bin/bash
sudo apt update
sudo apt install nginx

sudo vi /etc/nginx/sites-enabled/flask_app
#to be inside the file

server {
	listen 80;
	location / {
		proxy_pass http://127.0.0.1:5001;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

#disable nginix config file
sudo unlink /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/vite_app /etc/nginx/sites-enabled/

#check with this if okay
sudo nginx -t

#reload nginx
sudo nginx -s reload

